title: Preeyanuch Beawbungkerd
description: "Simple. Warm. Elegant."
theme: jekyll-theme-cayman
url: "https://Preeyanuchmimi.github.io"
author: Nuch
sass:
  style: compressed
  custom: "assets/css/custom.scss"

social_links:
  github: "https://github.com/Preeyanuchmimi"
  linkedin: "https://www.linkedin.com/in/preeyanuch"
  twitter: "https://twitter.com/username"

menu:
  - name: "Home"
    link: "/"
  - name: "About"
    link: "/about"
  - name: "Portfolio"
    link: "/portfolio"
  - name: "Contact"
    link: "/contact"

favicon: "/assets/images/favicon.ico"
